### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by TLi347** [Zhengxinyang/SDF-StyleGAN#1]
I am training following your setting. As shown below, after running "bash scripts/train_chairs.sh" type error occurs.

File "SDF-StyleGAN/network/model.py", line 526, in training_step
    self.manual_backward(total_gen_loss)
TypeError: cannot unpack non-iterable NoneType object

**Comment by Zhengxinyang** [comment]
I can't reproduce the issue. 

Did you configure the environment correctly? Can you show the detailed error messages?
