### ISSUE TITLE
pyrender.constants.RenderFlags.FACE_NORMALS flag while rendering images for FID calculation

### ISSUE THREAD

**Issue by wowo0709** [Zhengxinyang/SDF-StyleGAN#16]
Hi. Thanks for your great work!

I'm trying to compute FID score based on your codes of rendering fid images from given mesh.

Checking rendered images, I observed the rendered images looks like below.

![14](https://github.com/Zhengxinyang/SDF-StyleGAN/assets/70505378/449e1fb5-4c1a-48fc-8c1d-0705e73702e5)
![4](https://github.com/Zhengxinyang/SDF-StyleGAN/assets/70505378/41134c7a-324c-4a93-a025-d15ba75d6a5c)

And I found the normals are rendered because of the code below.
(Specifically, because of the flag pyrender.constants.RenderFlags.FACE_NORMALS)

https://github.com/Zhengxinyang/SDF-StyleGAN/blob/main/utils/render/render_utils.py#L157

What I want to ask is, why we need normals while computing FID scores.
Is it right to get the images as above and compute FID score with them?

Thanks

**Comment by Zhengxinyang** [comment]
Sorry, it's my mistake. We should remove the flag pyrender.constants.RenderFlags.FACE_NORMALS when computing FID scores.

**Comment by wowo0709** [comment]
Thank you for your fast reply!
