### ISSUE TITLE
Question about Shading-image-based FID

### ISSUE THREAD

**Issue by wenshuo128** [Zhengxinyang/SDF-StyleGAN#2]
Hi Xinyang, could you please tell me how many generated samples you used to calculate the shading-image-based FID for each category? I did not manage to find them in the paper. Thanks in advance :)

**Comment by Zhengxinyang** [comment]
We mention it in the last paragraph of section 4.1 of the paper

> For computing shading-image-based FID and FPD, Sr is formed by the meshes in the training set and |Sr| shapes are generated as Sg.

To give you an example, there are 6778 chairs in the ShapeNet, and 70% of them are taken as training set in our experiments, so we generate 4744 samples to calculate FID.

**Comment by wenshuo128** [comment]
I see. It makes sense. Thank you very much!
