### ISSUE TITLE
Training split ids 

### ISSUE THREAD

**Issue by ZENGXH** [Zhengxinyang/SDF-StyleGAN#3]
Hi xinyang, 

I am wondering if it's possible for you to provide the uids of the shapes in the training split? I would like to evaluate your released model and put it in the Table of our paper so I want to make sure our training split is the same. 

I try to download your released data in BaiduYun but the downloading speed is too slow here. It will be really helpful if I could get the uids directly.

**Comment by Zhengxinyang** [comment]
Our training data split follows [IM-GAN](https://github.com/czq142857/implicit-decoder), which is adapted from [HSP](https://github.com/chaene/hsp)

**Comment by Zhengxinyang** [comment]
The .txt files containing the data split are in the shapenet_data.tar.gz in  [HSP](https://github.com/chaene/hsp)
