### ISSUE TITLE
libEGL warning: failed to open /dev/dri/renderD128: Permission denied

### ISSUE THREAD

**Issue by PavanMantripragada** [Zhengxinyang/SDF-StyleGAN#8]
Followed these installation instructions.
```
pip install torch==1.8.0+cpu torchvision==0.9.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install fire scikit-image==0.18.2 scikit-learn==0.24.2 trimesh kornia==0.5.8 pyglet pyrender pyrr
pip install pytorch-lightning==1.5.1
```
I've tried to run the code with pytorch cpu and it gave the following error when I ran `bash scripts/generate_airplane.sh`

```
/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/distributed/_sharded_tensor/__init__.py:8: DeprecationWarning: torch.distributed._sharded_tensor will be deprecated, use torch.distributed._shard.sharded_tensor instead
  warnings.warn(
calculate self.av
Failed!
/home/mppavan/SDF-StyleGAN/torch_utils/ops/bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "/home/mppavan/SDF-StyleGAN/torch_utils/ops/bias_act.py", line 48, in _init
    _plugin = custom_ops.get_plugin('bias_act_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "/home/mppavan/SDF-StyleGAN/torch_utils/custom_ops.py", line 110, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1592, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1648, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

  warnings.warn('Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
start generation
  0%|                                                                                                           | 0/240 [00:00<?, ?it/s]libEGL warning: failed to open /dev/dri/renderD128: Permission denied

libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  0%|                                                                                                           | 0/240 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "generate.py", line 181, in <module>
    generate(model_path=args.model_path, output_path=args.output_path, ema=args.ema, level=args.level, mc_vol_size=args.mc_vol_size, num_generate=args.num_generate,
  File "generate.py", line 52, in generate
    image = render_mesh(mesh, index=index, resolution=render_resolution)/255
  File "/home/mppavan/SDF-StyleGAN/utils/render/render.py", line 38, in render_mesh
    triangle_id, rendered_image, normal_map, depth_image, p_images = render.render(path=None,
  File "/home/mppavan/SDF-StyleGAN/utils/render/render_utils.py", line 47, in render
    rendered_image, _ = pyrender_rendering(
  File "/home/mppavan/SDF-StyleGAN/utils/render/render_utils.py", line 142, in pyrender_rendering
    r = pyrender.OffscreenRenderer(SIZE, SIZE)
  File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f78d43a7540>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)                                                                                                    ) 
```   

will the code only work with the GPU version of pytorch?

**Comment by Zhengxinyang** [comment]
Based on your error message, it looks like you need to install opengl.

**Comment by Sunwenxin1** [comment]
> Followed these installation instructions.
> 
> ```
> pip install torch==1.8.0+cpu torchvision==0.9.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
> pip install fire scikit-image==0.18.2 scikit-learn==0.24.2 trimesh kornia==0.5.8 pyglet pyrender pyrr
> pip install pytorch-lightning==1.5.1
> ```
> 
> I've tried to run the code with pytorch cpu and it gave the following error when I ran `bash scripts/generate_airplane.sh`
> 
> ```
> /home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/distributed/_sharded_tensor/__init__.py:8: DeprecationWarning: torch.distributed._sharded_tensor will be deprecated, use torch.distributed._shard.sharded_tensor instead
>   warnings.warn(
> calculate self.av
> Failed!
> /home/mppavan/SDF-StyleGAN/torch_utils/ops/bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:
> 
> Traceback (most recent call last):
>   File "/home/mppavan/SDF-StyleGAN/torch_utils/ops/bias_act.py", line 48, in _init
>     _plugin = custom_ops.get_plugin('bias_act_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
>   File "/home/mppavan/SDF-StyleGAN/torch_utils/custom_ops.py", line 110, in get_plugin
>     torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
>   File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
>     return _jit_compile(
>   File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
>     _write_ninja_file_and_build_library(
>   File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1592, in _write_ninja_file_and_build_library
>     verify_ninja_availability()
>   File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1648, in verify_ninja_availability
>     raise RuntimeError("Ninja is required to load C++ extensions")
> RuntimeError: Ninja is required to load C++ extensions
> 
>   warnings.warn('Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
> start generation
>   0%|                                                                                                           | 0/240 [00:00<?, ?it/s]libEGL warning: failed to open /dev/dri/renderD128: Permission denied
> 
> libEGL warning: failed to open /dev/dri/renderD128: Permission denied
> 
>   0%|                                                                                                           | 0/240 [00:01<?, ?it/s]
> Traceback (most recent call last):
>   File "generate.py", line 181, in <module>
>     generate(model_path=args.model_path, output_path=args.output_path, ema=args.ema, level=args.level, mc_vol_size=args.mc_vol_size, num_generate=args.num_generate,
>   File "generate.py", line 52, in generate
>     image = render_mesh(mesh, index=index, resolution=render_resolution)/255
>   File "/home/mppavan/SDF-StyleGAN/utils/render/render.py", line 38, in render_mesh
>     triangle_id, rendered_image, normal_map, depth_image, p_images = render.render(path=None,
>   File "/home/mppavan/SDF-StyleGAN/utils/render/render_utils.py", line 47, in render
>     rendered_image, _ = pyrender_rendering(
>   File "/home/mppavan/SDF-StyleGAN/utils/render/render_utils.py", line 142, in pyrender_rendering
>     r = pyrender.OffscreenRenderer(SIZE, SIZE)
>   File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
>     self._create()
>   File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
>     self._platform.init_context()
>   File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 177, in init_context
>     assert eglInitialize(self._egl_display, major, minor)
>   File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
>     return self( *args, **named )
>   File "/home/mppavan/SDF-StyleGAN/stylegan2/lib/python3.8/site-packages/OpenGL/error.py", line 228, in glCheckError
>     raise GLError(
> OpenGL.error.GLError: GLError(
>         err = 12289,
>         baseOperation = eglInitialize,
>         cArguments = (
>                 <OpenGL._opaque.EGLDisplay_pointer object at 0x7f78d43a7540>,
>                 c_long(0),
>                 c_long(0),
>         ),
>         result = 0
> )                                                                                                    ) 
> ```
> 
> will the code only work with the GPU version of pytorch?

@PavanMantripragada hello, i also met this problem. have you solved it?
