### ISSUE TITLE
Minimum GPU requirements

### ISSUE THREAD

**Issue by benquick123** [Zhengxinyang/SDF-StyleGAN#9]
Hi, I see that you trained the models on 8x Nvidia V100 GPUs. However, I do not have this kind of processing power available; can you provide a rough estimate on the minimum required GPU to train this on?

**Comment by Zhengxinyang** [comment]
we trainedn models on the 8x Nvidia V100 GPUs to converge faster, you may notice that we use EMA to make the generator converges better. 
If you want to train our model on e.g. 1080 ti, it is possible to look at intermediate results without ema in 1-2 days (you can also try to reduce the local patch number to speed up the convergence)

**Comment by benquick123** [comment]
Ok, thanks. The main issue with my hardware is VRAM, but if 1080 is sufficient, then what I have available will also be.
